services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: honcho start
    plan: free
    envVars:
      - key: REDIS_URL
        fromSecret: redis-url
      - key: SECRET_KEY
        fromSecret: secret-key
      - key: DEBUG
        value: False
      - key: PYTHONUNBUFFERED
        value: 1
